language: node_js

node_js:
  - '6'

env:
  global:
    - secure: "oZo1mWz69bvOnArdxLXPa35IPBVIQiYCBA67qOtvhWtS4chFrxPAp/j3XI2q/tot2ck7sQCjJwiTFK5ZwZnE5/dpwbj9jAw+QPhWfVBYmbIrlO0LRC3tlnTGbcatEvBNyLf982lRUiahMHYbL7yLIh8iicLYaH6VXl4Y87XIXEVMkpCm1F/+qvHx8iM0WPB4phWgHFtNUPCIgWwtHLjqtfd7qZPop2SvqxX+MmBwV266/6zFXru68pd2NrJoTPAFCtpzy+zfmA+xRssUlEVzZ6ZEXHGbGL6NPZ8nsY+BJ1BD2Tx3zLH48Bo5Lwk8kN/GWU+d/nJhbktuPFaT9o4yhBzf7J40kTJSoe2jDwqfLyGIxTDKNvVHWzraf6ioGa4N2yM7UbflvaQuuMhQ5lrmG2csfxZPVguk5vSeR8HaltlobN4lbSut8ebOdt+RvmZdt5EvPtdm0fxMUEe1J3u2MKwjv5ajPBlWUgXZO0vbIjqTA67qqVhV0s7l0fMHg2ms94GZ9iwTlKTV99aZDPi0SCptHY3Fk3Qjz3xTu+2yHYu82ULUckV5jtnDjFdGdAXaD5Qs/ZyatCvvm8/vyyhd9NLjb9DDtNrNi4akH39bwuw11GYw3jyzfjFUtCrKrNVGiuRb1c4GOAG/rRyekYlw8O5I6s8JDQOEu+kqVnggAnM="

sudo: required

dist: trusty

addons:
  apt:
    packages:
      - google-chrome-stable
  firefox: "latest"

before_install:
  - firefox --version 2>/dev/null
  - google-chrome --product-version
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run lint
  - npm test
  - node ./bin/webcoach.js -b chrome https://www.sitespeed.io > output.json
  - node ./bin/webcoach.js -b firefox https://www.sitespeed.io > output.json
  - node ./bin/webcoach.js -b chrome --mobile https://www.sitespeed.io > output.json

deploy:
  provider: releases
  api_key: $GH_OAUTH
  file: 'dist/coach.bookmarklet.js'
  skip_cleanup: true
  on:
    tags: true
    node: '4.3'

notifications:
  slack:
    secure: Bo/bgmtFVGj6I2XnkvERfGnoM+t73WQSsP5eMlGM0jhUSKPqIc7Hf2zjYil3amMY3awFnoA6prILcMBzyUURj3jc5VRsWBCf6aQZ3bM+xzAcuTMcoiAKS7Ru1HQj1WY8G7VycDWuNeF8dCT0kt2QhcSneAUQ0qqyclWjcOK22kw=

cache:
  directories:
    - node_modules
